package com.ashampoo.kim.format.gif

public enum class GifChunkType {
    HEADER,
    LOGICAL_SCREEN_DESCRIPTOR,
    GLOBAL_COLOR_TABLE,
    LOCAL_COLOR_TABLE,
    IMAGE_DESCRIPTOR,
    IMAGE_DATA,
    GRAPHICS_CONTROL_EXTENSION,
    PLAIN_TEXT_EXTENSION,
    APPLICATION_EXTENSION,
    COMMENT_EXTENSION,
    TERMINATOR
}
